name: openvpn_flutter_example
description: Demonstrates how to use the openvpn_flutter plugin. 
publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0" 
dependencies:
  flutter:
    sdk: flutter

  flutter_openvpn_plugin:
    path: ../ 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0
 
flutter: 
  uses-material-design: true 